### ISSUE TITLE
 Error uploading esp32 

### ISSUE THREAD

**Issue by wj7106** [MathieuDeprez/ESP32_DSLR_ASSISTANT#1]
I can't upload to esp32. I've tried many times. Using platform IO will show an error and the burning can't be on the board. Can you explain the burning steps in detail, thank you! 
 I see Canon files in your lib library. Do you know if my Canon camera can be used?

**Comment by wj7106** [comment]
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
-----------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32dev.html
PLATFORM: Espressif 32 (3.4.0) > Espressif ESP32 Dev Module
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 31 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <USB Host Shield Library 2.0> 1.4.0
|   |-- <SPI> 1.0
|-- <PTP_ESP>
|   |-- <BluetoothSerial> 1.0
|   |-- <USB Host Shield Library 2.0> 1.4.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <SSD_13XX> 1.0
|   |   |-- <SPI> 1.0
|-- <SSD_13XX> 1.0
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio/build/esp32dev/src/main.cpp.o
In file included from lib/PTP_ESP/ptpdpparser.h:22:0,
                 from lib/PTP_ESP/main.h:10,
                 from src/main.cpp:1:
lib/PTP_ESP/valuelist.h:20:20: fatal error: eeprom.h: No such file or directory

****************************************************************
* Looking for eeprom.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:eeprom.h"
* Web  > https://platformio.org/lib/search?query=header:eeprom.h
*
****************************************************************

compilation terminated.
Compiling .pio/build/esp32dev/lib666/PTP_ESP/input.cpp.o
Compiling .pio/build/esp32dev/lib666/PTP_ESP/modCam.cpp.o
In file included from lib/PTP_ESP/ptpdpparser.h:22:0,
                 from lib/PTP_ESP/main.h:10,
                 from lib/PTP_ESP/input.cpp:1:
lib/PTP_ESP/valuelist.h:20:20: fatal error: eeprom.h: No such file or directory

****************************************************************
* Looking for eeprom.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:eeprom.h"
* Web  > https://platformio.org/lib/search?query=header:eeprom.h
*
****************************************************************

compilation terminated.
In file included from lib/PTP_ESP/ptpdpparser.h:22:0,
                 from lib/PTP_ESP/main.h:10,
                 from lib/PTP_ESP/modCam.cpp:1:
lib/PTP_ESP/valuelist.h:20:20: fatal error: eeprom.h: No such file or directory

****************************************************************
* Looking for eeprom.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:eeprom.h"
* Web  > https://platformio.org/lib/search?query=header:eeprom.h
*
****************************************************************

compilation terminated.
*** [.pio/build/esp32dev/src/main.cpp.o] Error 1
*** [.pio/build/esp32dev/lib666/PTP_ESP/input.cpp.o] Error 1
*** [.pio/build/esp32dev/lib666/PTP_ESP/modCam.cpp.o] Error 1

**Comment by MathieuDeprez** [comment]
I @wj7106 ,
Can you share with me the error message so that I can help you?

I don't think it will work with your Canon camera on the current state but I don't think it will require a lot of changes to make it work. My library is inspired by **felis/PTP_2.0** library, in this repo, you will find the differences between Canon and Nikon functions and so you can adapt my library.

**Comment by wj7106** [comment]
Thank you for your reply. I changed your lib library, and there are more errors. I also need to match the android app. Some instructions are a little messy. Please help me adapt canon. Thank you

**Comment by MathieuDeprez** [comment]
I,
Again, if you don't share with me the error messages, I am not able to help...

Which instructions are you referring to?

For the Canon adaptation, you can see in the main.cpp file that I use
`Nikon Nik(&Usb, &CamStates);` line 316
To make it work with the Canon camera, you have to change that object with the equivalent for Canon.  (`CanonEOS    Eos(&Usb, &CamStates);` I suppose)
You will find example codes in this library : https://github.com/felis/PTP_2.0

**Comment by wj7106** [comment]
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32doit-devkit-v1.html
PLATFORM: Espressif 32 (3.4.0) > DOIT ESP32 DEVKIT V1
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 33 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <USB Host Shield Library 2.0> 1.4.0
|   |-- <SPI> 1.0
|-- <PTP_ESP>
|   |-- <BluetoothSerial> 1.0
|   |-- <USB Host Shield Library 2.0> 1.4.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <SSD_13XX> 1.0
|   |   |-- <SPI> 1.0
|-- <SSD_13XX> 1.0
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio/build/esp32doit-devkit-v1/src/devpropparser.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/src/main.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/canoneos.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/eoseventparser.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/input.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/modCam.cpp.o
src/main.cpp: In function 'void handleTimeLapse(Canon&)':
src/main.cpp:41:15: error: 'class Canon' has no member named 'waitCameraReady'
         canon.waitCameraReady(3000);
               ^
src/main.cpp:44:15: error: 'class Canon' has no member named 'waitCameraReady'
         canon.waitCameraReady(10000);
               ^
src/main.cpp:47:15: error: 'class Canon' has no member named 'waitCameraReady'
         canon.waitCameraReady(3000);
               ^
src/main.cpp: In member function 'virtual uint8_t Canon::Poll()':
src/main.cpp:102:33: error: 'setShutterSpeed' was not declared in this scope
                 setShutterSpeed();
                                 ^
src/main.cpp:106:29: error: 'setAperture' was not declared in this scope
                 setAperture();
                             ^
src/main.cpp:110:24: error: 'setIso' was not declared in this scope
                 setIso();
                        ^
src/main.cpp:114:25: error: 'getInfo' was not declared in this scope
                 getInfo();
                         ^
src/main.cpp:118:29: error: 'setExpoBias' was not declared in this scope
                 setExpoBias();
                             ^
src/main.cpp:122:34: error: 'moveFocusAndroid' was not declared in this scope
                 moveFocusAndroid();
                                  ^
src/main.cpp:126:34: error: 'takePhotoAndroid' was not declared in this scope
                 takePhotoAndroid();
                                  ^
src/main.cpp:130:46: error: 'takeTimeLapse' was not declared in this scope
                 takeTimeLapse(TIMER_TIMELAPSE);
                                              ^
src/main.cpp:142:26: error: 'tryFocus' was not declared in this scope
                 tryFocus();
                          ^
src/main.cpp:146:25: error: 'takeHdr' was not declared in this scope
                 takeHdr();
                         ^
src/main.cpp:150:34: error: 'takeLongExposure' was not declared in this scope
                 takeLongExposure();
                                  ^
src/main.cpp:154:35: error: 'downloadThumbnail' was not declared in this scope
                 downloadThumbnail();
                                   ^
src/main.cpp:158:39: error: 'getAndSendListHandles' was not declared in this scope
                 getAndSendListHandles();
                                       ^
src/main.cpp:162:30: error: 'downloadJpeg' was not declared in this scope
                 downloadJpeg();
                              ^
src/main.cpp:174:32: error: 'downloadJpegHq' was not declared in this scope
                 downloadJpegHq();
                                ^
src/main.cpp:185:30: error: 'stopLiveView' was not declared in this scope
                 stopLiveView();
                              ^
src/main.cpp:193:36: error: 'getLiveView' was not declared in this scope
             bool buf = getLiveView();
                                    ^
src/main.cpp:201:31: error: 'startLiveView' was not declared in this scope
                 startLiveView();
                               ^
src/main.cpp:208:60: error: 'GetLiveViewImageV2' was not declared in this scope
                 GetLiveViewImageV2(response, responseLenght);
                                                            ^
src/main.cpp:212:94: error: 'sendBluetoothData' was not declared in this scope
                 sendBluetoothData(MyBluetoothCode::LiveViewImageOut, response, responseLenght);
                                                                                              ^
src/main.cpp:235:28: error: 'printEvent' was not declared in this scope
         printEvent(bufEvent);
                            ^
src/main.cpp:249:34: error: 'takeHdr' was not declared in this scope
                 takeHdr(hdrParams);
                                  ^
src/main.cpp:277:78: error: 'GetObjectHandlesV2' was not declared in this scope
                 GetObjectHandlesV2(0xFFFFFFFF, 0, 0, response, responseLenght);
                                                                              ^
src/main.cpp:287:61: error: 'sendObjectHandlesBt' was not declared in this scope
                 sendObjectHandlesBt(response, responseLenght);
                                                             ^
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/ptp.cpp.o
Compiling .pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/ptpconstitles.cpp.o
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::SetImageQuality(uint32_t)':
lib/PTP_ESP/canoneos.cpp:140:84: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, NULL, void*)'
  if ( (ptp_error = Transaction(EOS_OC_SetDevicePropValue, &flags, NULL, (void*)&sup)) != PTP_RC_OK)
                                                                                    ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::SetPCConnectMode(uint8_t)':
lib/PTP_ESP/canoneos.cpp:150:53: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [1])'
  return Operation(EOS_OC_SetPCConnectMode, 1, params);
                                                     ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::SetExtendedEventInfo(uint8_t)':
lib/PTP_ESP/canoneos.cpp:157:57: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [1])'
  return Operation(EOS_OC_SetExtendedEventInfo, 1, params);
                                                         ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::StartBulb()':
lib/PTP_ESP/canoneos.cpp:168:29: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [3])'
  Operation(0x911A, 3, params);
                             ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp:169:27: error: no matching function for call to 'CanonEOS::Operation(int, int, NULL)'
  Operation(0x911B, 0, NULL);
                           ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp:170:27: error: no matching function for call to 'CanonEOS::Operation(int, int, NULL)'
  Operation(0x9125, 0, NULL);
                           ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::StopBulb()':
lib/PTP_ESP/canoneos.cpp:182:29: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [3])'
  Operation(0x911A, 3, params);
                             ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp:185:29: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [3])'
  Operation(0x911A, 3, params);
                             ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp:186:27: error: no matching function for call to 'CanonEOS::Operation(int, int, NULL)'
  Operation(0x9126, 0, NULL);
                           ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp:187:27: error: no matching function for call to 'CanonEOS::Operation(int, int, NULL)'
  Operation(0x911C, 0, NULL);
                           ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::CancelTransfer(uint32_t)':
lib/PTP_ESP/canoneos.cpp:197:51: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [1])'
  return Operation(EOS_OC_CancelTransfer, 1, params);
                                                   ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::ResetTransfer(uint32_t)':
lib/PTP_ESP/canoneos.cpp:205:50: error: no matching function for call to 'CanonEOS::Operation(int, int, uint32_t [1])'
  return Operation(EOS_OC_ResetTransfer, 1, params);
                                                  ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::MoveFocus(uint16_t)':
lib/PTP_ESP/canoneos.cpp:235:70: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, uint32_t [1], NULL)'
  if ( (ptp_error = Transaction(EOS_OC_MoveFocus, &flags, params, NULL)) != PTP_RC_OK)
                                                                      ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'virtual uint16_t CanonEOS::EventCheck(PTPReadParser*)':
lib/PTP_ESP/canoneos.cpp:246:60: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, NULL, PTPReadParser*&)'
  if ( (ptp_error = Transaction(0x9116, &flags, NULL, parser)) != PTP_RC_OK)
                                                            ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::Capture()':
lib/PTP_ESP/canoneos.cpp:254:42: error: no matching function for call to 'CanonEOS::Operation(int, int, NULL)'
  return Operation(EOS_OC_Capture, 0, NULL);
                                          ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:141:14: note: candidate: uint16_t PTP::Operation(MyOpCode, uint8_t, uint32_t*)
     uint16_t Operation(MyOpCode opcode, uint8_t nparams = 0, uint32_t *params = NULL);
              ^
lib/PTP_ESP/ptp.h:141:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::SetProperty(uint16_t, uint32_t)':
lib/PTP_ESP/canoneos.cpp:268:86: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, NULL, void*)'
  if ( (ptp_error = Transaction(EOS_OC_SetDevicePropValue, &flags, NULL, (void*)params)) != PTP_RC_OK)
                                                                                      ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::GetProperty(uint16_t, PTPReadParser*)':
lib/PTP_ESP/canoneos.cpp:282:88: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, uint32_t [1], void*)'
  if ( (ptp_error = Transaction(EOS_OC_GetDevicePropValue, &flags, params, (void*)parser)) != PTP_RC_OK)
                                                                                        ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::GetDeviceInfoEx(PTPReadParser*)':
lib/PTP_ESP/canoneos.cpp:293:83: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, NULL, void*)'
  if ( (ptp_error = Transaction(EOS_OC_GetDeviceInfoEx, &flags, NULL, (void*)parser)) != PTP_RC_OK)
                                                                                   ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
lib/PTP_ESP/canoneos.cpp: In member function 'uint16_t CanonEOS::GetObject(uint32_t, uint32_t, PTPReadParser*)':
lib/PTP_ESP/canoneos.cpp:308:79: error: no matching function for call to 'CanonEOS::Transaction(int, PTP::OperFlags*, uint32_t [2], void*)'
  if ( (ptp_error = Transaction(EOS_OC_GetObject, &flags, params, (void*)parser)) != PTP_RC_OK)
                                                                               ^
In file included from lib/PTP_ESP/canoneos.h:27:0,
                 from lib/PTP_ESP/canoneos.cpp:17:
lib/PTP_ESP/ptp.h:124:14: note: candidate: uint16_t PTP::Transaction(MyOpCode, PTP::OperFlags*, uint32_t*, void*)
     uint16_t Transaction(MyOpCode opcode, OperFlags *flags, uint32_t *params, void *pVoid);
              ^
lib/PTP_ESP/ptp.h:124:14: note:   no known conversion for argument 1 from 'int' to 'MyOpCode'
*** [.pio/build/esp32doit-devkit-v1/src/main.cpp.o] Error 1
*** [.pio/build/esp32doit-devkit-v1/libec1/PTP_ESP/canoneos.cpp.o] Error 1
======================================= [FAILED] Took 1.65 seconds =======================================

**Comment by MathieuDeprez** [comment]
@wj7106 ,
Here is the thing: in the PTP_2.0 library, there is a **Nikon** and a **CanonEOS** class.
In my library, I added some functions to the Nikon class like `setShutterSpeed()` for example. So you have to add all theses new functions in the CanonEOS class.
That doesn't mean it will work right away after that. Indeed, if there are two classes (Nikon and Canon), it is because both of these constructors don't use the same "Operation Code" to do the same thing. Example: to get the shutter speed in Canon, you have to send an "A" command but in Nikon, you have to send a "B" command.

When I wrote my library, I had just a Nikon with me so all my functions are understandable by Nikon but not necessarily by Canon (even if most of the time, the commands are the same). 

What you need to do:

- Copy all the functions that I created from the Nikon class to the Canon class.
- Test if all these functions work like that. If not, you probably just have to change the **operation code** of the function with the Canon version of it. You can find lists of **operation code** on the internet, here is one example: https://github.com/gphoto/libgphoto2/blob/master/camlibs/ptp2/ptp.h

**Comment by wj7106** [comment]
OK, I'll try to modify it
